server:
  port: 9090

spring:
  application:
    name: eureka-client-service
eureka:
  client:
    service-url:
      defaultZone:  ${EUREKA_URI:http://eureka-1-server.com:9001/eureka/, http://eureka-2-server.com:9002/eureka/, http://eureka-3-server.com:9003/eureka/}